# Generated by Django 2.0 on 2017-12-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='work name')),
                ('work_description', models.TextField(verbose_name='work description')),
                ('started_at', models.DateTimeField(verbose_name='work started at')),
                ('ended_at', models.DateTimeField(verbose_name='work ended at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
    ]
